### ISSUE TITLE
Backtest report seems to return wrong results

### ISSUE THREAD

**Issue by frin1** [c9s/bbgo#916]
When backtesting bollmaker (or any other strategy) I get a higher profit if I specify higher fees.
E.g. backtest result of the default bollmaker.yaml config (with makerFeeRate and takerFeeRate to 0.0%):
![image](https://user-images.githubusercontent.com/35973823/188325239-66c888ec-a3cc-46fb-b6e6-c0f76630e217.png)

When backtesting the same config, but added makerFeeRate and takerFeeRate to 0.075%:
![image](https://user-images.githubusercontent.com/35973823/188325266-3f96a62f-701c-485c-8280-777b4f18df0a.png)

The fees are specified like this:
![image](https://user-images.githubusercontent.com/35973823/188325356-68b333a6-2c00-45ed-8b14-68c3331ae71d.png)

Also I am not able to calculate  the “FINAL TOTAL BALANCE” with the same results as the report gives when specifying fees > 0.0%. I’ve tried to calculate based on “INITIAL TOTAL BALANCE” + profit (including unrealized profit) +- fees, but I did not get the same result. The closesed I get is about 100 USD difference, so it is not so much, but unless I am missing something, I would guess that if you know how much the profit, fee and initial balance is, you should get pretty accurate calculation of the final balance?

**Comment by c9s** [comment]
i guess this is the main branch version, yes I have found the fee issue, will take a look tomorrow

**Comment by c9s** [comment]
@frin1 I read your screenshots very carefully, but it looks make sense to me

basically, you can't use init balance, fee and the profit to check if the final balance is correct or not. because the realized profit is already in the usdt balance, and that balance might have been used to hold some base asset.   You can have to consider the holding position as well. In this case, you hold 2.65 ETH with average cost 3787.6399, and so the back-test calculates your unrealized profit 6492.1819

In the default backtest feeMode, it deducts your fee from the quote balance, which in your case is the USDT.

The "profit" does not count the fee, the profit is calculated from your trades, and the position.

**Comment by c9s** [comment]
https://github.com/c9s/bbgo/pull/917 might be related, I am not sure.  the fee token issue is now fixed and merged into the main branch.

**Comment by frin1** [comment]
Sorry, my mistake. I guess 2.65 ETH is rounded, so then it makes sense. 
Based on my calculations I got that the final balance should be **3651.43** in USDT based on:
Initial balance + Realized profit - Unrealized profit - fees.

However, considering that 2.65 ETH + 24.83 USDT gives *3569.89 USDT**, and 2.65 ETH is probably rounded this makes sense.
